### ISSUE TITLE
Create canned data and reference it in setup instructions

### ISSUE THREAD

**Issue by edwinsteele** [goodtune/firelocs#6]
Canned data should:
* Be stored in the repo
* Have enough events that we can do meaningful drill down (but not so many that students will find the volume overwhelming), say 15 ish?
* Show the enumeration of alert levels (Advice, Watch and Act, Emergency, NA)
* Be used in the commands included in the README for setup

Also make reference to the live data URL so that students feel linked to the RFS, and also so that they can test their code against different/more events if they want.

**Comment by goodtune** [comment]
I think 15-30 so we can have enough variability as they filter their views.

Update the getting started instructions in the README to load from `data/demonstration.xml` and relocate the RFS live-load instruction to a sub-section _Loading RFS data_.
