### ISSUE TITLE
Enable github pages for this repo

### ISSUE THREAD

**Issue by edwinsteele** [goodtune/firelocs#8]
I'll serve the slides directly from github (and let the students follow on themselves, so they can be self-paced if they wish). I can't make this change because it's your repo, so please:

1. Go to _Settings_ for this repo
1. Under _GitHub Pages_, select the source as "master branch /docs folder"
1. Confirm that the slides are visible at https://goodtune.github.io/firelocs  (might take a few minutes to publish, and *may* need a push to trigger)

**Comment by goodtune** [comment]
Well that was easy!
