### ISSUE TITLE
Expose lat lon in model (?)

### ISSUE THREAD

**Issue by edwinsteele** [goodtune/firelocs#9]
On of our our tasks involves enriching the json endpoint with lat long (so we can subsequently consume that in the mapping step). I'm on the fence about having the students to modify the model, do any migration (if indeed it's necessary) in addition to adjusting the parsing in `import_fires.py` and any rendering in the json.

Is it reasonable to have students adjust the model, the importing code and do any db migration (perhaps blowing away is simpler). What do you think?

**Comment by goodtune** [comment]
On reflection, I'm leaning towards adding the fields for them - we don't have that long, and even though migrations are easy when adding columns, it's distant last in learning value for a session of this length.

I will add them as individual columns (as decimal value) and leave them unpopulated by the import script. This will leave it as a task for the students to populate the data prior to consuming it.

**Comment by edwinsteele** [comment]
Thanks. Adding a migration (even though we didn't need it) is a nice reference point for anyone wanting to see the process.
